apiVersion: v1
kind: Pod
metadata:
  name: test-gpu-pod
  namespace: default
spec:
  containers:
    - name: gpu-test
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    node-role: training
  restartPolicy: Never
